spacing:
  max_row: 2
  around_operators: true
  after_commas: true
  around_keywords: true

empty_lines:
  max_consecutive_empty_lines: 2

naming:
  variables: camelCase
  constants: UPPER_CASE
  methods: camelCase
  classes: PascalCase
