spacing:
  max_row: 2
  around_operators: true
  after_commas: true
  around_keywords: true
naming:
  variables: camelCase
  constants: UPPER_CASE
  methods: camelCase
  classes: PascalCase
max_consecutive_empty_lines: 2
usage:
  unused_vars: true
  unused_methods: true
complexity:
  max_complexity: 9
